app:
  name: 'backend-trainee-assignment-2023'
  version: '2023.0.0'

http:
  port: 8080
  site_url: localhost:8080

logger:
  log_level: 'info'

postgres:
  url: "postgres://user:pass@localhost:5432/postgres"
  pool_max: 10